FROM busybox
MAINTAINER Robert Brem <brem_robert@hotmail.com>

VOLUME /dokuwiki/data/pages
VOLUME /dokuwiki/data/meta
VOLUME /dokuwiki/data/media
VOLUME /dokuwiki/data/media_attic
VOLUME /dokuwiki/data/media_meta
VOLUME /dokuwiki/data/attic
VOLUME /dokuwiki/conf
VOLUME /var/log

CMD /bin/sh
    
    
    