FROM busybox
MAINTAINER Robert Brem <brem_robert@hotmail.com>

VOLUME /opt/jboss/wildfly/standalone/deployments
VOLUME /opt/jboss/wildfly/standalone/configuration
VOLUME /opt/jboss/wildfly/modules

CMD /bin/sh
